test_square (__main__.TestExercice) ... ERROR
test_square_root (__main__.TestExercice) ... ok

======================================================================
ERROR: test_square (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 17, in test_square
    output_exo = list(map(exercice.square, self.numbers))
  File "/home/runner/work/c01_ch3_exercice1-jeansffrt/c01_ch3_exercice1-jeansffrt/exercice.py", line 10, in square
    squared = math.pow(squared, 2)
UnboundLocalError: local variable 'squared' referenced before assignment

----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=1)
